### ISSUE TITLE
[WIN32] Weird behavior lowest-rightmost CMD character

### ISSUE THREAD

**Issue by Zorgatone** [tapio/rlutil#14]
I have this sourcecode: [Crook - Roguelike](https://github.com/Zorgatone/crook/blob/3e2e1ac7988b60a895a1f8265f0745a748b80067/src/crook.c) (`bug-wincmd` branch on file `src/crook.c`, commit `3e2e1ac`)

I'm having a very weird issue on the windows' CMD prompt.
I am saving the coordinates correctly (AFAICT), and I'm debugging the player position and the arrow pressed.

If you can test this, go to the lower-rightmost position in the terminal. Everytime `x == maxx && y == maxy` both the debug info and the player are printed one line above

**Comment by Zorgatone** [comment]
@tapio after further investigation I noticed that when in that position the CMD scrolls down its buffer.

Any way to fix this? Is it a problem with the engine, or shold I just move again to (1, 1) after writing to that position?

**Comment by Zorgatone** [comment]
Maybe we can use a function that can add a character without advancing the cursor?

**Comment by nabijaczleweli** [comment]
Can confirm bug

**Comment by Zorgatone** [comment]
@nabijaczleweli if you're on windows you can clone the repo and test. I don't know if OS X or Linux have the same issue or not

**Comment by nabijaczleweli** [comment]
Hrmmm, apparently my message wasn't clear enough.
I meant, that I can confirm it (the issue), but am not sure, whether it is a bug.

**Comment by Zorgatone** [comment]
Oh, ok thanks

**Comment by Zorgatone** [comment]
Is it possible to modify/print a character on a given position(x, y) without moving the cursor?
That will help a lot to solve this

**Comment by nabijaczleweli** [comment]
Try the one wevuse in `cls()` to fill the screen with `' '`, maybe?

**Comment by Zorgatone** [comment]
[**@nabijaczleweli**](https://github.com/nabijaczleweli) commented on [17 nov 2015, 14:44 CET](https://github.com/tapio/rlutil/issues/14#issuecomment-157373589 "2015-11-17T13:44:10Z - Replied by Github Comment Enhancer"):
> Try the one wevuse in `cls()` to fill the screen with `' '`, maybe?

I don't get what you're trying to say. I don't want to clear the screen :stuck_out_tongue_winking_eye:

**Comment by nabijaczleweli** [comment]
I meant the `FillConsoleOutputCharacter()` WinAPI function (or the like)

**Comment by Zorgatone** [comment]
That won't be of any use if I don't want to fill the entire screen with the same character.

That's not what is causing the problem with the player being in the low-right corner

**Comment by nabijaczleweli** [comment]
[`WriteConsoleOutputCharacter()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687410%28v=vs.85%29.aspx) sounds like something we could use

**Comment by nabijaczleweli** [comment]
How should the function (in `rlutil`) be called?

**Comment by Zorgatone** [comment]
I'm used to use ncurses' "addch(char)" and "mvaddch(row,col,char)". I don't
know if those names would fit for rlutil though.
>
> Maybe a simpler name would be cool

**Comment by nabijaczleweli** [comment]
I'm gonna hold off starting work on this, because my other PRs (#17 and #19) explode the codebase quite a lot already (i.e. merging it will be a PITA).

**Comment by Zorgatone** [comment]
Ok, cool

**Comment by nabijaczleweli** [comment]
@Zorgatone I was aiming for something different, because the arguments are in a different order and it *will* be quite confusing

**Comment by Zorgatone** [comment]
Yeah ok.
What about this?

```C
/* return_type */ setChar(int ch);
/* return_type */ setCharAt(int ch, int row, int col);

//  (returning void for nothing, or int for cursor's current position)
```

**Comment by nabijaczleweli** [comment]
`int` can't be used for cursor position, but, other than that, it looks alright

**Comment by nabijaczleweli** [comment]
Also works on Linux now

**Comment by nabijaczleweli** [comment]
How does one even print to an arbitrary position on Linux (without `<ESC>[6n`, which doesn't work)? Google just gives me shitposts and repeated data on moving the cursor and querying terminal size.

**Comment by Zorgatone** [comment]
I have absolutely no idea

**Comment by nabijaczleweli** [comment]
*teethgrind*

**Comment by nabijaczleweli** [comment]
Okay, this looks literally impossible, even using `[n]curses` (like in https://github.com/nabijaczleweli/rlutil/commit/72f640699cb9108262590916812622cf26757a71) leaves off `H1` on the end of each line and requires moving the cursor.

**Comment by Zorgatone** [comment]
Still somehow world be good to prevent that CMD issue.

Maybe just moving the cursor home every time it goes beyond the maximum
lines and maximum columns.
Or just using some Windows API to set the buffer's number of rows just to
the visible ones.

**Comment by nabijaczleweli** [comment]
You can locate() to the last position and then setChar() there. Or, alternatively, use the setCharAt() implementation on my fork (on mobile rn, so no link).

Actually, we could just have setCharAt() with a working body on Windooze and an assert() (with an "if you know how to do it, plz show us" message, mebbe)/return an error code.

**Comment by Zorgatone** [comment]
Oh you already have done those two functions? Nice

**Comment by nabijaczleweli** [comment]
Well, `setCharAt()` is a terrible failure on Linux, but it's trivial on Windows: https://github.com/tapio/rlutil/blob/72f640699cb9108262590916812622cf26757a71/rlutil.h

**Comment by Zorgatone** [comment]
You could have that on windows, and on other platforms just save the old position, move to new position, print character normally, restore previous position.

That's a bit of an hack, but it should work at least for now :laughing:

**Comment by Zorgatone** [comment]
`setCharAt` and `Test 12: Non-advancing character setting` worked on `Mac OS X`

**Comment by nabijaczleweli** [comment]
Hrmmm, interesting. It leaves `H1` after each line on an `ssh`d-into Ubuntu 13.04 LTS Headless x86 on Windows 10 x86_64

**Comment by nabijaczleweli** [comment]
@Zorgatone How about `Test 13: Positioned character setting`?

**Comment by Zorgatone** [comment]
No wait, nevermind.... On non-blocking input there are some random characters appearing:


```
Test 8: Non-blocking keyboard input
You should be able to move the '@' character with WASD keys.
Hit Space to continue to the next test.
Turn count: 71149d
                           
                            
                               
                 w              
                                 
                                @
             














```

**Comment by Zorgatone** [comment]
Also this on arrow keys:
```
Test 9: Arrow keys
You should be able to move the '@' character with arrow keys.
Hit Escape to continue to the next test.

        [C                
       ^[[D              @    
                            [[C
      ^[[B                    
                              
                      ^[[A
                     
           ^[[D      
                     
                     
                     










```

**Comment by Zorgatone** [comment]
But the 12th test works, haven't seen a 13th though

**Comment by nabijaczleweli** [comment]
Pull https://github.com/nabijaczleweli/rlutil/commit/72f640699cb9108262590916812622cf26757a71

**Comment by nabijaczleweli** [comment]
@Zorgatone Those weird results happen when invoked normally or when piping?

**Comment by Zorgatone** [comment]
Same tests 8 and 9 (printing wasd and arrow characters from input), and this is test 13:
```
Press any key to continue...r setting
Next ASCII characters should appear rapidly after each other in a 15-width pattern.
!"#$%&'()*+,-./ remain blinking in the same position.
0123456789:;<=>
?@ABCDEFGHIJKLM
NOPQRSTUVWXYZ[\
]^_`abcdefghijk
lmnopqrstuvwxyz
{|}~















```

**Comment by nabijaczleweli** [comment]
*teethgrind* Still OSX?
...
Fuck OSX

**Comment by Zorgatone** [comment]
lolol, it's not the non-standard `iTerm` here... I don't really care about `iTerm` at all.

It's the system default `Terminal.app` I'm talking about, yes still OS X.

**Comment by Zorgatone** [comment]
What are this two files?

Could we add those and the binaries to the `.gitignore` and `make clean`?

```
TR:rlutil tommaso$ cat Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -g -O2 -Wall -Wextra

all: test example-c

test: rlutil.h test.cpp
	$(CXX) $(CFLAGS) -lncurses -o test test.cpp

example-c: rlutil.h example.c
	$(CC) $(CFLAGS) -o example-c example.c
	
.PHONY: clean

clean:
	rm -f test example-c

TR:rlutil tommaso$ make clean
rm -f test example-c
TR:rlutil tommaso$ git status
On branch positioned-character
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	example-c.dSYM/
	test.dSYM/

nothing added to commit but untracked files present (use "git add" to track)

```

**Comment by nabijaczleweli** [comment]
These files aren't.

No; they exist only in your head.

**Comment by Zorgatone** [comment]
They appeared when I runned `make`

**Comment by nabijaczleweli** [comment]
s/runned/ran/

Remove them, rerun `make`.
What toolchain?

**Comment by Zorgatone** [comment]
```
TR:rlutil tommaso$ ls
Makefile		docs			rlutil.h
README.markdown		example.c		test.cpp
cross-compile.sh	index.html
TR:rlutil tommaso$ make
g++ -I. -g -O2 -Wall -Wextra -lncurses -o test test.cpp
gcc -I. -g -O2 -Wall -Wextra -o example-c example.c
TR:rlutil tommaso$ which gcc; gcc -v; which g++; g++ -v
/usr/bin/gcc
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
/usr/bin/g++
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
TR:rlutil tommaso$ 
```

**Comment by nabijaczleweli** [comment]
What's the `ls` after `make`?

**Comment by Zorgatone** [comment]
See the updated log, I forgot to paste it

**Comment by nabijaczleweli** [comment]
W*h*ell, that's surprising. Works On My Machines:tm:, though

**Comment by nabijaczleweli** [comment]
Also, [Google it](https://www.google.pl/search?q=.dsym+file&ie=utf-8&oe=utf-8&gws_rd=cr&ei=NyNPVoCaBYLfywPuhZyIDA)

**Comment by Zorgatone** [comment]
We can just add an entry on `.gitignore` and `make` clean for any files with the `dSYM` extension though.

Just to clean the crap out before pulling other changes.

Yeah I googled that XD

**Comment by Zorgatone** [comment]
That's probably because my toolchain is logged in with my Apple Developer ID (OS X, iOS), and is generating those.

The issue wasn't what exactly are those files, but if we could just get rid of those doing `make clean`, and ignoring them from the repo in `.gitignore`.

If those aren't just when building your fork, I'll open a PR separately.

**Comment by nabijaczleweli** [comment]
They are independent of any code, it's just Apple badness

**Comment by nabijaczleweli** [comment]
Can you confirm, that the issue is solved by `locate()`ing to the bottomrightmost position and using `setChar()`?

**Comment by Zorgatone** [comment]
Yes it's working.. (I had to edit the makefile because I didn't have ncurses on windows, but it worked).

See anyhow this screenshots when running the cpp tests.

As you can see I can move outside the current screen bounds and go all the way down the CMD buffer :fearful: 

non blocking
![non blocking](http://i.imgur.com/YUJYWhs.png)
arrows
![arrows](http://i.imgur.com/UXc5IG9.png)
test 13 - positioning
![non blocking](http://i.imgur.com/UHjV6C9.png)

**Comment by nabijaczleweli** [comment]
If they're working, I believe this is closeable?

**Comment by nabijaczleweli** [comment]
We should have, like, `setString()`, to print a string without moving the cursor.

**Comment by Zorgatone** [comment]
Yep

**Comment by nabijaczleweli** [comment]
PR underway... right now
