### ISSUE TITLE
Intensity handling with resetColor()

### ISSUE THREAD

**Issue by tapio** [tapio/rlutil#16]
Regarding #5 and #15, the color can now be reset, but the intensity (that some terminals display as bold font) is not handled, at least with ANSI. This can be seen at least on Gnome Terminal with the test.cpp program as after reseting the color after the first test, all following text appears bold and not regular weight.

I think there should be some discussion whether the resetColor() function should reset other text styling attributes too, or if we should support that with separate functions. Then again Windows CMD probably offers rather limited support for styling and I think the current behaviour of resetColor() there is to reset all attributes.

**Comment by nabijaczleweli** [comment]
[These](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682088%28v=vs.85%29.aspx#_win32_character_attributes) are all character attributes Windows can handle, and they are all that is saved in `saveDefaultColor()`.

**Comment by nabijaczleweli** [comment]
Could you test https://github.com/nabijaczleweli/rlutil/commit/bbc86915d518ef3218b4233f0998fec46e2d21e0 on Linux?
