### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by Zorgatone** [tapio/rlutil#18]
Is there any support for background colors?
If not, could we have it added? :smile:

**Comment by nabijaczleweli** [comment]
Лет'с сее

**Comment by Zorgatone** [comment]
:+1: :smile:

**Comment by nabijaczleweli** [comment]
Please test the [`background-color`](https://github.com/nabijaczleweli/rlutil/tree/background-color) branch on my fork

**Comment by Zorgatone** [comment]
Working fine on Windows' `CMD`. Tested on Windows 10, with raster fonts

**Comment by Zorgatone** [comment]
How do you reset the background color?

For me `resetColor()` is resetting the foreground color correctly. But when I `cls()` the screen after that reset, I still get the wrong background

**Comment by Zorgatone** [comment]
Example:

```C
#include <stdio.h>
#include <stdlib.h>

#include "rlutil.h"

int main(void) {
    cls();

	saveDefaultColor();

	setBackgroundColor(WHITE);
	setColor(BLACK);

    printf("Hello world!\n");

    getch();

    resetColor();

    cls(); // Here the CMD is GREY on WHITE instead of GREY on BLACK

    return 0;
}
```

**Comment by nabijaczleweli** [comment]
Interesting

**Comment by Zorgatone** [comment]
The CPP test seemed to work corretly though. Could it be just C?

**Comment by Zorgatone** [comment]
Oh nevermind. That was because you were resetting it explicitly to black again

**Comment by nabijaczleweli** [comment]
I forgot to reset all attributes in `resetColor()`, your example works now

**Comment by Zorgatone** [comment]
Good I'll try tomorrow :smile:

**Comment by nabijaczleweli** [comment]
Windows fix pushed, still not sure if works with ANSI

**Comment by nabijaczleweli** [comment]
Fixed, submitting a PR

**Comment by tapio** [comment]
Closing since, nabijaczleweli's implementation is merged to master.
