### ISSUE TITLE
Use "\033c" instead of "\033[2J" to clear whole buffer?

### ISSUE THREAD

**Issue by Zorgatone** [tapio/rlutil#22]
I've tried to use "\033c" instead of "\033[2J" to clear whole buffer.

It works on Mac and git-bash/cygwin.

This clears the whole buffer instead of adding a ton of newlines to `clear` the screen (fixes: #10).

The downside of this is that also reset all attributes.

[See the link](http://www.termsys.demon.co.uk/vtansi.htm)

**Comment by nabijaczleweli** [comment]
I had this on a branch somewhere before (and it worked perfectly). Add it to #21?

**Comment by Zorgatone** [comment]
The part about the attributes being reset, could be confusing though...

**Comment by nabijaczleweli** [comment]
Nah, it's only used in `cls()`, which, as the [docs](https://github.com/nabijaczleweli/rlutil/blob/master/rlutil.h#L522) for it say and it [explicitly does this](https://github.com/nabijaczleweli/rlutil/blob/master/rlutil.h#L541)

**Comment by Zorgatone** [comment]
Ok then :)

However take a look on how they are clearing the screen with ANSI here, they are printing three escapes:

https://github.com/substack/node-charm/blob/master/index.js#L110

```JavaScript
Charm.prototype.reset = function (cb) {
    // resets the screen on iTerm, which appears
    // to lack support for the reset character.
    this.write(encode('[0m'));
    this.write(encode('[2J'));

    this.write(encode('c'));
    return this;
};
```

**Comment by Zorgatone** [comment]
I think this could be added to #21, indeed

**Comment by nabijaczleweli** [comment]
It now is

**Comment by Zorgatone** [comment]
:+1:

**Comment by Zorgatone** [comment]
Lol, you should print all three escape strings on mac, or even in all systems (just in case someother shitty terminal won't support "\033c"
