### ISSUE TITLE
Defining min/max is a bad idea

### ISSUE THREAD

**Issue by nabijaczleweli** [tapio/rlutil#27]
Especially since it's done *after* everything else, not bringing anything to the table

**Comment by nabijaczleweli** [comment]
Shall I submit a PR?

**Comment by Zorgatone** [comment]
What min/max do you mean?
Terminal size?

**Comment by nabijaczleweli** [comment]
No, [this](https://github.com/tapio/rlutil/blob/master/rlutil.h#L696-L714)

**Comment by tapio** [comment]
I think those are a left over from days past when I though to put various utilities here instead of just console I/O. I've been lately thinking of removing them too.

**Comment by Zorgatone** [comment]
I don't see whether this could any good or bad at all.

I don't see the point in having or remove that at all... It's just some pointless piece of code IMHO

**Comment by nabijaczleweli** [comment]
If it's pointless, it shall be purged!

(also, it's not pointless. it's literally damaging)

**Comment by nabijaczleweli** [comment]
@tapio You know merging that PR would've autoclosed this issue as well?

**Comment by tapio** [comment]
> You know merging that PR would've autoclosed this issue as well?

That's what I did, which you can see in that message: "tapio closed this in #28 an hour ago"

**Comment by Zorgatone** [comment]
Drunk @nabijaczleweli
😂
